////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the index.adoc page used in the general 'Installing Jenkins'
page.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker-for-tutorials.adoc (used in
_run-jenkins-in-docker.adoc).
////


=== Linux containers on Windows

The Jenkins project provides both Linux and link:https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=windows[Windows container images].
However, this tutorial specifically focuses on the Linux container images.
Therefore, ensure that your Docker for Windows installation is configured to run Linux Containers rather than link:https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce[Windows Containers].
You can refer to the Docker documentation for instructions on how to link:https://docs.docker.com/desktop/wsl/[use Linux containers].


=== Start your Jenkins instance

1. Obtain the latest Jenkins instance, customized for this tutorial, by cloning the link:https://github.com/jenkins-docs/quickstart-tutorials.git[quickstart-tutorials repository].
2. After cloning, navigate to the `quickstart-tutorials` directory, and execute the command `docker compose up -d` to run the example.
3. Once the containers are running successfully (you can verify this with `docker compose ps`), the controller can be accessed at http://localhost:8080.

If you are unable to install `docker compose` on your machine for any reason, you can still run the example in the cloud for free thanks to link:https://www.gitpod.io/[GitPod]. GitPod link:https://www.gitpod.io/pricing[is free] for 50 hours per month.
You need to link it to your GitHub account so you can run the example in the cloud.
Click on link:https://gitpod.io/?autostart=true#https://github.com/jenkins-docs/quickstart-tutorials[that link] to open a new browser tab with a GitPod workspace where you'll be able to start the Jenkins instance, and run the rest of the tutorial.

Now, log in using the `admin` username and `admin` password on link:http://localhost:8080[localhost:8080].

[[accessing-the-jenkins-blue-ocean-docker-container]]
== Accessing the Docker container

If you want to access your Docker container through a terminal/command prompt using the link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`] command, add an option like `--name jenkins-tutorial` to the `docker exec` command.
That will access the Jenkins Docker container named "jenkins-tutorial".

You can access your docker container (through a separate terminal/command prompt window) with a `docker exec` command such as:

`docker exec -it jenkins-blueocean bash`

[[accessing-the-jenkins-console-log-through-docker-logs]]
== Accessing the Docker logs

You may want to access the Jenkins console log, for instance, when <<unlocking-jenkins,Unlocking Jenkins>> as part of the <<setup-wizard,Post-installation setup wizard>>.

Access the Jenkins console log through the terminal/command prompt window from which you executed the `docker run ...` command.
Alternatively, you can also access the Jenkins console log through the link:https://docs.docker.com/engine/reference/commandline/logs/[Docker logs] of your container using the following command:

`docker logs <docker-container-name>`

Your `<docker-container-name>` can be obtained using the `docker ps` command.


== Accessing the Jenkins home directory

You can access the Jenkins home directory, to check the details of a Jenkins build in the `workspace` subdirectory, for example.

If you mapped the Jenkins home directory (`/var/jenkins_home`) to one on your machine's local file system, for example, in the `docker run ...` command <<downloading-and-running-jenkins-in-docker,above>>, access the directory contents through your machine's usual terminal/command prompt.

If you specified the `--volume jenkins-data:/var/jenkins_home` option in the `docker run ...` command, access the contents of the Jenkins home directory through your container's terminal/command prompt using the link:https://docs.docker.com/engine/reference/commandline/container_exec/[`docker container exec`] command:

`docker container exec -it <docker-container-name> bash`

As per <<accessing-the-jenkins-console-log-through-docker-logs,the previous section>>, get your `<docker-container-name>` using the link:https://docs.docker.com/engine/reference/commandline/container_ls/[`docker container ls`] command.
If you specified the `--name jenkins-blueocean` option in the `docker container run ...`  command above (refer to <<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue Ocean Docker container>> if needed), use the `docker container exec` command:

`docker container exec -it jenkins-blueocean bash`

////
Might wish to add explaining the `docker run -t` option, which was covered in
the old installation instructions but not above.

Also mention that spinning up a container of the `jenkins/jenkins` Docker
image can be done so with all the same
https://github.com/jenkinsci/docker#usage[configuration options] available to
the other images published by the Jenkins project.

Explain colon syntax on Docker image references like
`jenkins/jenkins:latest'.
////
