---
layout: section
title: Docker
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the
'tutorials/_prerequisites.adoc' file, which is used in the Guided Tour of the
Jenkins Documentation.
////

link:https://docs.docker.com/get-started/overview/[Docker] is a platform for running applications in an isolated environment called a "container" (or Docker container).
Applications like Jenkins can be downloaded as read-only "images" (or Docker images), each of which is run in Docker as a container.
A Docker container is a "running instance" of a Docker image.
A Docker image is stored permanently, based on when image updates are published, whereas containers are stored temporarily.
Learn more about these concepts in link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation and setup] in the Docker documentation.

Due to Docker's fundamental platform and container design, a Docker image for a given application, such as Jenkins, can be run on any supported operating system or cloud service also running Docker.
Supported operating systems include macOS, Linux and Windows, and supported cloud services include AWS and Azure.

include::doc/book/installing/_new_prerequisites.adoc[]

=== Installing Docker

To install Docker and Docker Compose on your operating system, first, ensure that you have the correct <<prerequisites,Prerequisites>> as outlined above.
Then, navigate to the link:https://docs.docker.com/get-docker/[Docker documentation website] and select the Docker Desktop version suitable for your operating system.
If you’re using a cloud service or a machine without a GUI, you can proceed to install the Docker Engine only from link:https://docs.docker.com/engine/install/[this page].
Follow the installation instructions provided on their website.

Additionally, you will need to install Docker Compose.
While it’s included in the Docker Desktop installation for Windows, Linux, and macOS, you will need to install it separately if you only installed the Docker Engine.
Follow the link:https://docs.docker.com/compose/install/linux/#install-using-the-repository[instructions] provided on the Docker documentation website for Linux, these link:https://docs.docker.com/compose/install/standalone/#on-windows-server[instructions] for Windows, or these link:https://www.ionos.com/digitalguide/server/configuration/docker-compose-on-mac/[instructions] for macOS.

[CAUTION]
====
If you are installing Docker on a Linux-based operating system, ensure you configure Docker so it can be managed as a non-root user.
Read more about this in Docker's link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation steps for Linux] page of their documentation.
This page also contains information about how to configure Docker to start on boot.
====

=== Downloading and running Jenkins in Docker

There are several Docker images of Jenkins available.

We recommend using the official link:https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=lts-jdk17[`jenkins/jenkins:lts-jdk17`] image from the Docker Hub repository.
This image contains the current link:/download[Long-Term Support (LTS) release of Jenkins], which is production-ready.
However, this image does not include the plugins you may need for your Jenkins instance, requiring you to install them manually later on.
In this guide, we propose two ways of doing this:

1. First, use Docker Compose to quickly set up a running Jenkins instance with a nice set of plugins in a matter of seconds.
2. Second, use Docker Compose to run the installation wizard, giving you a better understanding of what happens under the hood.

[NOTE]
====
A new `jenkins/jenkins` Docker image is published each time a new release of Jenkins is published.
You can see a list of previously published versions of the `jenkins/jenkins` image on the link:https://hub.docker.com/r/jenkins/jenkins/tags/[tags] page.
====

include::doc/book/installing/_docker_quickstart.adoc[]

include::doc/book/installing/_setup-wizard-for-tutorials.adoc[]
