---
layout: section
title: Docker
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the
'tutorials/_prerequisites.adoc' file, which is used in the Guided Tour of the
Jenkins Documentation.
////

link:https://docs.docker.com/get-started/overview/[Docker] is a platform for running applications in an isolated environment called a "container" (or Docker container).
Applications like Jenkins can be downloaded as read-only "images" (or Docker images), each of which is run in Docker as a container.
A Docker container is a "running instance" of a Docker image.
A Docker image is stored permanently, based on when image updates are published, whereas containers are stored temporarily.
Learn more about these concepts in link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation and setup] in the Docker documentation.

Due to Docker's fundamental platform and container design, a Docker image for a given application, such as Jenkins, can be run on any supported operating system or cloud service also running Docker.
Supported operating systems include macOS, Linux and Windows, and supported cloud services include AWS and Azure.

include::doc/book/installing/_new_prerequisites.adoc[]

=== Installing Docker

To install Docker and Docker Compose on your operating system, first, ensure that you have the correct <<prerequisites,Prerequisites>> as outlined above.
Then, navigate to the link:https://docs.docker.com/get-docker/[Docker documentation website] and select the Docker Desktop version suitable for your operating system.
If you’re using a cloud service or a machine without a GUI, you can proceed to install the Docker Engine only from link:https://docs.docker.com/engine/install/[this page].
Follow the installation instructions provided on their website.

Additionally, you will need to install Docker Compose.
While it’s included in the Docker Desktop installation for Windows, Linux, and macOS, you will need to install it separately if you only installed the Docker Engine.
Follow the link:https://docs.docker.com/compose/install/linux/#install-using-the-repository[instructions] provided on the Docker documentation website for Linux, these link:https://docs.docker.com/compose/install/standalone/#on-windows-server[instructions] for Windows, or these link:https://www.ionos.com/digitalguide/server/configuration/docker-compose-on-mac/[instructions] for macOS.

If you are unable to install `docker compose` on your machine for any reason, you can still run the example in the cloud for free thanks to link:https://www.gitpod.io/[GitPod]. GitPod link:https://www.gitpod.io/pricing[is free] for 50 hours per month.
You need to link it to your GitHub account so you can run the example in the cloud.
Click on link:https://gitpod.io/?autostart=true#https://github.com/jenkins-docs/quickstart-tutorials[that link] to open a new browser tab with a GitPod workspace where you'll be able to start the Jenkins instance, and run the rest of this guide.

docker versions updatecli

[CAUTION]
====
If you are installing Docker on a Linux-based operating system, ensure you configure Docker so it can be managed as a non-root user.
Read more about this in Docker's link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation steps for Linux] page of their documentation.
This page also contains information about how to configure Docker to start on boot.
====

=== Linux containers on Windows

The Jenkins project provides both Linux and link:https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=windows[Windows container images].
However, this tutorial specifically focuses on the Linux container images.
Therefore, ensure that your Docker for Windows installation is configured to run Linux Containers rather than link:https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce[Windows Containers].
You can refer to the Docker documentation for instructions on how to link:https://docs.docker.com/desktop/wsl/[use Linux containers].

=== Downloading and running Jenkins in Docker

There are several Docker images of Jenkins available.

We recommend using the official link:https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=lts-jdk17[`jenkins/jenkins:lts-jdk17`] image from the Docker Hub repository.
This image contains the current link:/download[Long-Term Support (LTS) release of Jenkins], which is production-ready.

[NOTE]
====
A new `jenkins/jenkins` Docker image is published each time a new release of Jenkins is published.
You can see a list of previously published versions of the `jenkins/jenkins` image on the link:https://hub.docker.com/r/jenkins/jenkins/tags/[tags] page.
====

However, this image does not include the plugins you may need for your Jenkins controller, requiring you to install them manually later on.
In this guide, we propose two ways of doing this:

1. First, use Docker Compose to run the installation wizard, which will provide you with a better understanding of the underlying processes.
2. Second, leverage Docker Compose to swiftly set up a Jenkins controller and an agent equipped with a comprehensive set of plugins, all within a matter of seconds.


include::doc/book/installing/_docker_not_so_quick_start.adoc[]
include::doc/book/installing/_docker_quickstart.adoc[]

////
include::doc/book/installing/_setup-wizard-for-tutorials.adoc[]
////
